# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da9c9a8c8ffb3b8c598fbfc03a72f53feae25c0fd4755a3cd74a4e6d81139c4d356e82af922dad961788e1c6cdfaf8f273b603e3966cb834a3ced631cac6156d

test:
  secret_key_base: b2437f24d993657b2ac99378a765a94d9ef073f470ac6f6520bd66eb9e500fb01c99701a844cf5119db15a88ffdbfe6f7e74216b62c230b25c7b94d5a0b84228

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
